---
title: "Flight Delay Analysis"
author: "Bartosz Bronikowski"
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
library(DBI)
library(odbc)

settings <- Sys.getenv(c("ODBC_DRIVER", "DB_SERVER", "DBNAME"))
stopifnot(all(nzchar(settings)))
connection <- dbConnect(
  odbc(),
  Driver = settings[["ODBC_DRIVER"]],
  Server = settings[["DB_SERVER"]],
  Database = settings[["DBNAME"]],
  Trusted_Connection = "True"
)
knitr::opts_chunk$set(echo = FALSE)
```

## Arrival delays

All delay values are in minutes.

```{sql connection=connection, output.var="delay_summary"}
SELECT AVG(arr_delay_new) AS average_delay,
       MAX(arr_delay_new) AS maximum_delay
FROM Flight_delays;
```

```{r}
knitr::kable(delay_summary)
```

## Flights with the longest delay

```{sql connection=connection, output.var="longest_delays"}
SELECT fl_date, carrier, origin_city_name, dest_city_name, arr_delay_new
FROM Flight_delays
WHERE arr_delay_new = (SELECT MAX(arr_delay_new) FROM Flight_delays);
```

```{r}
knitr::kable(longest_delays)
```

## Average arrival delay by weekday

```{sql connection=connection, output.var="weekday_delays"}
SELECT weekday_name, AVG(arr_delay_new) AS average_delay
FROM Weekdays
INNER JOIN Flight_delays ON weekday_id = Flight_delays.day_of_week
GROUP BY weekday_name
ORDER BY average_delay DESC;
```

```{r}
knitr::kable(weekday_delays)
```

## Average arrival delay by airline

```{sql connection=connection, output.var="airline_delays"}
SELECT airline_name, AVG(arr_delay_new) AS average_delay
FROM Flight_delays
INNER JOIN Airlines ON Flight_delays.airline_id = Airlines.airline_id
GROUP BY airline_name
ORDER BY average_delay DESC;
```

```{r}
knitr::kable(airline_delays)
```

## Correlation between arrival and departure delays

```{sql connection=connection, output.var="delay_correlation"}
WITH delays AS (
    SELECT CAST(arr_delay_new AS FLOAT) AS arrival,
           CAST(dep_delay_new AS FLOAT) AS departure
    FROM Flight_delays
    WHERE arr_delay_new IS NOT NULL AND dep_delay_new IS NOT NULL
)
SELECT (SUM(arrival * departure) - SUM(arrival) * SUM(departure) / COUNT(*))
       / NULLIF(
           SQRT(SUM(arrival * arrival) - SUM(arrival) * SUM(arrival) / COUNT(*))
           * SQRT(SUM(departure * departure) - SUM(departure) * SUM(departure) / COUNT(*)),
           0
       ) AS pearson_correlation
FROM delays;
```

```{r}
knitr::kable(delay_correlation)
```

## Average arrival delay through day 23

```{sql connection=connection, output.var="early_month_delays"}
SELECT airline_id, AVG(arr_delay_new) AS average_delay
FROM Flight_delays
WHERE day_of_month <= 23
GROUP BY airline_id;
```

```{r}
knitr::kable(early_month_delays)
```

```{r disconnect, include=FALSE}
dbDisconnect(connection)
```
